-- Add sample real-looking events so you can see the UI working
-- while we debug the Eventbrite API integration

INSERT INTO senior_events (
    title, description, category, start_datetime, end_datetime,
    city, venue, latitude, longitude, is_online, registration_url,
    organizer_name, source_platform, senior_relevance_score,
    verified, approved, tags
) VALUES
-- Upcoming events in next few days
('Morning Yoga for Seniors', 
 'Gentle yoga session designed specifically for seniors aged 60+. Focus on flexibility, balance, and breathing exercises. All levels welcome. Mats provided.',
 'fitness', 
 NOW() + INTERVAL '2 days', 
 NOW() + INTERVAL '2 days' + INTERVAL '1 hour',
 'Mumbai', 
 'Wellness Center, Bandra West',
 19.0596, 72.8295,
 false,
 'https://www.eventbrite.com/e/yoga-seniors-mumbai',
 'Mumbai Wellness Foundation',
 'eventbrite',
 0.92,
 true, true,
 ARRAY['yoga', 'fitness', 'wellness', 'seniors']),

('Free Health Checkup Camp',
 'Comprehensive health screening for senior citizens including blood pressure, blood sugar, BMI, eye checkup, and consultation with doctors. Free of cost.',
 'health_wellness',
 NOW() + INTERVAL '5 days',
 NOW() + INTERVAL '5 days' + INTERVAL '3 hours',
 'Delhi',
 'Community Health Center, Dwarka Sector 10',
 28.5921, 77.0460,
 false,
 'https://www.eventbrite.com/e/health-camp-delhi',
 'Delhi Health Services',
 'eventbrite',
 0.95,
 true, true,
 ARRAY['health', 'checkup', 'free', 'seniors']),

('Online Meditation & Mindfulness',
 'Daily guided meditation sessions via Zoom. Learn breathing techniques, mindfulness practices, and stress management. Perfect for beginners.',
 'spiritual',
 NOW() + INTERVAL '1 day',
 NOW() + INTERVAL '1 day' + INTERVAL '45 minutes',
 'Online',
 NULL, NULL, NULL,
 true,
 'https://zoom.us/j/meditation-seniors',
 'Inner Peace Foundation',
 'eventbrite',
 0.88,
 true, true,
 ARRAY['meditation', 'online', 'spiritual', 'mindfulness']),

('Senior Citizens Monthly Meetup',
 'Community gathering with lunch, games, cultural programs, and social activities. Meet new friends and enjoy quality time together.',
 'social_community',
 NOW() + INTERVAL '7 days',
 NOW() + INTERVAL '7 days' + INTERVAL '4 hours',
 'Bengaluru',
 'Senior Citizens Association Hall, Indiranagar',
 12.9716, 77.5946,
 false,
 'https://www.eventbrite.com/e/senior-meetup-bangalore',
 'Bangalore Senior Citizens Association',
 'eventbrite',
 0.90,
 true, true,
 ARRAY['community', 'social', 'seniors', 'meetup']),

('Smartphone Basics Workshop',
 'Learn to use WhatsApp, video calls, online banking, and digital payments safely. Hands-on training with personal assistance.',
 'learning',
 NOW() + INTERVAL '4 days',
 NOW() + INTERVAL '4 days' + INTERVAL '2 hours',
 'Chennai',
 'Public Library, T Nagar',
 13.0418, 80.2341,
 false,
 'https://www.eventbrite.com/e/smartphone-workshop-chennai',
 'Digital Literacy Foundation',
 'eventbrite',
 0.93,
 true, true,
 ARRAY['technology', 'learning', 'smartphone', 'seniors']),

('Classical Music Concert',
 'Evening of Hindustani classical music featuring renowned artists. Special seating arrangements for senior citizens. Tea and snacks included.',
 'arts_culture',
 NOW() + INTERVAL '10 days',
 NOW() + INTERVAL '10 days' + INTERVAL '2 hours',
 'Mumbai',
 'Nehru Centre Auditorium, Worli',
 19.0144, 72.8179,
 false,
 'https://www.eventbrite.com/e/classical-music-mumbai',
 'Mumbai Music Circle',
 'eventbrite',
 0.82,
 true, true,
 ARRAY['music', 'classical', 'culture', 'concert']),

('Laughter Yoga Session',
 'Join us for laughter yoga and fun activities. Proven health benefits including stress relief and improved mood. All ages welcome, seniors encouraged!',
 'social_community',
 NOW() + INTERVAL '3 days',
 NOW() + INTERVAL '3 days' + INTERVAL '1 hour',
 'Pune',
 'Koregaon Park',
 18.5362, 73.8958,
 false,
 'https://www.eventbrite.com/e/laughter-yoga-pune',
 'Pune Laughter Club',
 'eventbrite',
 0.87,
 true, true,
 ARRAY['laughter', 'social', 'wellness', 'fun']),

('Online Cooking Class - Healthy Recipes',
 'Learn healthy traditional Indian recipes perfect for seniors. Interactive session with Q&A. Recipes designed for diabetic-friendly and heart-healthy diets.',
 'learning',
 NOW() + INTERVAL '6 days',
 NOW() + INTERVAL '6 days' + INTERVAL '1.5 hours',
 'Online',
 NULL, NULL, NULL,
 true,
 'https://zoom.us/j/cooking-class',
 'Culinary Heritage India',
 'eventbrite',
 0.85,
 true, true,
 ARRAY['cooking', 'online', 'healthy', 'traditional']),

('Morning Walk Group',
 'Daily morning walks in the park. Make new friends while staying fit! Organized by certified fitness instructor. Free to join.',
 'fitness',
 NOW() + INTERVAL '1 day',
 NOW() + INTERVAL '1 day' + INTERVAL '1 hour',
 'Hyderabad',
 'Lumbini Park',
 17.4126, 78.4719,
 false,
 'https://www.eventbrite.com/e/morning-walk-hyderabad',
 'Hyderabad Fitness Club',
 'eventbrite',
 0.86,
 true, true,
 ARRAY['walking', 'fitness', 'outdoor', 'social']),

('Bhajan Sandhya',
 'Evening devotional singing session. Tea and snacks provided. Open to all, no prior singing experience needed.',
 'spiritual',
 NOW() + INTERVAL '2 days',
 NOW() + INTERVAL '2 days' + INTERVAL '2 hours',
 'Ahmedabad',
 'Community Temple, Navrangpura',
 23.0359, 72.5559,
 false,
 'https://www.eventbrite.com/e/bhajan-ahmedabad',
 'Spiritual Society Ahmedabad',
 'eventbrite',
 0.89,
 true, true,
 ARRAY['bhajan', 'spiritual', 'devotional', 'community']);

-- Success message
SELECT 
    COUNT(*) as total_events,
    'Sample events added! Visit /services/companionship to see them.' as message
FROM senior_events
WHERE approved = true;
